### ISSUE TITLE
Doc: no license specified

### ISSUE THREAD

**Issue by Anemy** [kgolid/chromotome#1]
Couldn't find a file or mention in the source - is there a license?

I dig the library and would like to use it if possible in one or two of my apps :)
Keep up the sweet art kgolid!

**Comment by Anemy** [comment]
oops just saw it's `MIT` in the package.json - perhaps add a LICENSE file?
Thanks!

**Comment by kgolid** [comment]
Hey, thank you for noticing and letting me know! Will add the missing LICENSE file :)
